### ISSUE TITLE
v1 API documentation

### ISSUE THREAD

**Issue by wittydeveloper** [frontier-forms/frontier-forms#1]
It's super important for us to stick to a target API design by writing a API documentation.
This should include:
- available components (+ props for each)
- other APIs

**Comment by wittydeveloper** [comment]
**Idea**: Split the exposed components in 2 types: `<Form>` and `<FormKit>`

`<FormKit>` takes a `UIKit` (type to components mapping) and a GQL mutation.
`<Form>` takes only a GQL mutation and a render props.

**Comment by chmelevskij** [comment]
I think `<Form>` would still be made of `<FormKit>` and etc. The top level component should definitely be just `<Form>` accepting the GQL mutation as required param and then, but it still should allow the same props optionally as `<FormKit>` for convenience.

**Comment by wittydeveloper** [comment]
@chmelevskij I agree on that, let's unify the thing with one component.
I'll update the doc.
