### ISSUE TITLE
UI-kit render props missing `save` modifier

### ISSUE THREAD

**Issue by lukasluecke** [frontier-forms/frontier-forms#18]
Is it possible that the `save` modifier to submit the form is not being provided as expected? I only get the individual field modifiers (`change` etc.), and could only find those in the code as well.

**Comment by wittydeveloper** [comment]
Hi @lukasluecke ,

Saving the form is achievable using the `form` render props argument as shown below:

```tsx
<Frontier /* ... */>
{
  (form) => 
    // ...
    form.submit();
    // ...
}
</Frontier>
```

**Comment by lukasluecke** [comment]
I think you mean `({form})` - but this means that the documentation is incorrect, both for the UI-kit and the "normal" part, since both of those show and use `modifiers.save.

I guess it's your decision wether users should have to handle the form submit logic (see my PR #19) or if it could be abstracted by the library (i.e. cancel the submit event).
