### ISSUE TITLE
[SUGGESTION] Show error message/logs when Frontier/Apollo Client failed to connect to API endpoint

### ISSUE THREAD

**Issue by melvinkcx** [frontier-forms/frontier-forms#43]
When I first added Frontier, I copied and paste the example code from the documentation, it works perfectly fine. However, when I changed the Apollo Client to point to another port in my localhost, the UI stopped being rendered, and no error messages are found. 

After spending some time debugging, I realize my React proxy is not properly set up, thus I got a network error as such:
![DeepinScreenshot_select-area_20191111115508](https://user-images.githubusercontent.com/16914545/68557765-2a466880-047a-11ea-8319-0b0947fb8485.png)

Suggestions for situation like this would be:
1. writing some logs to the console when an error has occurred internally,
2. render the components despite errors caused by Apollo Client

**Comment by melvinkcx** [comment]
Investigated this issue, it is rooted from ApolloClient, here is the issue:
https://github.com/apollographql/apollo-feature-requests/issues/153

A workaround is to introduce `apollo-link-http` with `apollo-client` as suggested in the issue above.

I think this is beyond the scope of `frontier-forms`. Feel free to close this @wittydeveloper

**Comment by charlypoly** [comment]
Yup, it's kind of linked to #31 and #52 
Let's drop this introspection request in #52, it will solve this issue
Form rendering should not be request-bound 🙂
